### ISSUE TITLE
Not working on custom banners.

### ISSUE THREAD

**Issue by andrewkm** [pustinek/ItemFilter#1]
@pustinek
We have a WHITE_BANNER that looks as such:
https://i.imgur.com/XIP7SCh.png

The item filter does not work on this sort of item.
A fix for this would be great!

**Comment by pustinek** [comment]
Hey,
It's because of the `ignore_custom_items: true` setting it configs.yml file. Set it to `false` and it should work

**Comment by andrewkm** [comment]
Fixed by changing that config, thank you!
