### ISSUE TITLE
Itemfitler not building.

### ISSUE THREAD

**Issue by andrewkm** [pustinek/ItemFilter#10]
Plugin no longer builds after change to `<groupId>me.pustinek</groupId>`

`[ERROR] Failed to execute goal on project ItemFilter: Could not resolve dependencies for project me.pustinek:ItemFilter:jar:2.1.0: Failed to collect dependencies at me.pustinek:interactivemessenger-bukkit:jar:1.3.2: Failed to read artifact descriptor for me.pustinek:interactivemessenger-bukkit:jar:1.3.2: Could not transfer artifact me.pustinek:interactivemessenger-bukkit:pom:1.3.2 from/to nlthijs48 (http://maven.wiefferink.me/): Transfer failed for http://maven.wiefferink.me/me/pustinek/interactivemessenger-bukkit/1.3.2/interactivemessenger-bukkit-1.3.2.pom: Unknown host maven.wiefferink.me -> [Help 1]`

**Comment by andrewkm** [comment]
Full build log:
https://gist.githubusercontent.com/andrewkm/898bb9bc9508a1d0325142f68eef3244/raw/2b7fda5a18cca7de404caffced3e43d070ad29b8/gistfile1.txt

Used to build just fine prior to these changes.

**Comment by pustinek** [comment]
Yeah I uploaded it since it was requested by some users on discord, even though it was mentioned to not be working, since some dependencies were moved/removed. I'll  try to find the time to fix it this month, but can't promise anything since I'm kinda busy with other stuff.

**Comment by andrewkm** [comment]
Thanks a lot @pustinek would be very helpful so we can continue using the latest! <3

**Comment by andrewkm** [comment]
@pustinek do you have any update on this?

**Comment by pustinek** [comment]
> @pustinek do you have any update on this?

Yeah, I have a plan to fix the whole plugin probably the week after 11 of january. 
Dislocated my shoulder a week ago, so I'm having a hard time doing anything on my pc 😅

**Comment by andrewkm** [comment]
@pustinek poke. <3

**Comment by Nuckerr** [comment]
> Yeah I uploaded it since it was requested by some users on discord, even though it was mentioned to not be working, since some dependencies were moved/removed. I'll try to find the time to fix it this month, but can't promise anything since I'm kinda busy with other stuff.

Where did you upload this?

**Comment by andrewkm** [comment]
I think this project should be archived at this point sadly. :(
@pustinek

**Comment by pustinek** [comment]
Did some updating. So feel free to test it out if everything works correctly, I also moved the project from maven to Gradle

**Comment by andrewkm** [comment]
@pustinek
This did not fix building the project. You did not address the original issue at all.
Full build log: https://pastebin.com/raw/5pJdJJ9X

**Could not find me.pustinek:interactivemessenger:1.2.1**
Please fix your gradle/project setup.

Also your wrapper isn't working due to permissions issues, we must invoke gradle version ourselves on jenkins.

**Comment by pustinek** [comment]
The issue is with github packages, you have to setup authentication with it even if the package is public. 
I'll move it it to something like maven central this evening

**Comment by Nuckerr** [comment]
The problem is retrieving interactive-messanger. But you can now get this from jitpack, so if you add the jitpack repo and slightly change that dependency, it does build.

**Comment by andrewkm** [comment]
@pustinek can you do that?

**Comment by pustinek** [comment]
With the latest update does it not work ? I moved the dependency to maven central so "mavencentral()" repo should fix this no ?

**Comment by pustinek** [comment]
Sorry about that, I forgot to click publish :no_mouth:

**Comment by Nuckerr** [comment]
That works now thank you. Just on a side note your replacements aren't working, for example the plugin's version is `${version}`

**Comment by andrewkm** [comment]
Fixed now and building correctly. Thanks :)

**Comment by andrewkm** [comment]
> That works now thank you. Just on a side note your replacements aren't working, for example the plugin's version is `${version}`

I believe they worked for me... https://i.imgur.com/ZQ2UNUd.png
