### ISSUE TITLE
Reload command - resets language files.

### ISSUE THREAD

**Issue by andrewkm** [pustinek/ItemFilter#13]
Reload command - resets language files.
Make edits, use /if reload in game or in console, language files reset.
It should reload them not reset them.

Only way I can actually get the language files to change is if I edit them in the actual compiled jar @pustinek

**Comment by pustinek** [comment]
You need to copy the default.yml file into something like "EN.yml" and then in configs.yml change the property:
`language: EN`

This is so when new "text" is added you can copy it from the default.yml

**Comment by andrewkm** [comment]
@pustinek that should be in the release xP
Can you please add that.

**Comment by andrewkm** [comment]
Forked and maintaining on our end, dev is MIA.
