### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Sikatsu** [pustinek/ItemFilter#2]
If I give the player itemfilter.toggle and itemfilter.menu, they can toggle and open the menu.

When the player disables picking up a certain item and toggle the item filter on, they can still pick it up unless I also add itemfilter.add and itemfilter.remove, but I don't want them to use that feature.

When I added itemfilter.use, and disabled itemfilter.add and itemfilter.remove, they couldn't open the menu anymore.

I have a feeling the permissions need to be looked at if possible ^^

**Comment by pustinek** [comment]
Hey,
I kinda bootstraped the permission system toggether in the last minute. Will look into it and roll out a new version in the next day. Thanks for letting me know 😁

**Comment by Sikatsu** [comment]
Thank you!
