### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ghost** [pustinek/ItemFilter#6]
Hello pustinek!
I am struggling to recompile this plugin into a functional jar file on your latest version by using cmd prompt and messing with files... I am new to java and don't really know how everything works yet. If you could please make a new release with the complete jar file attached that would be really nice and super helpful to me and probably some other people who want to download/decompile and edit your plugin :D
Thank you!! (sorry, I'm not too sure if this is the correct spot to leave feedback or ask questions but I couldn't find anywhere else.)

**Comment by pustinek** [comment]
Hey there,
I'm not really an expert when it comes to maven and java. But you should be able to just clone the project, download the dependencies and compile. It should work just fine and I would recommend you use intellij idea makes the process much easier.
For the latest releases you should visit the spigot page https://www.spigotmc.org/resources/itemfilter-1-13-filter-pickup.70334/
but I will also upload the latest versions here just in case :D
