### ISSUE TITLE
Someone stole your code.

### ISSUE THREAD

**Issue by dpvb** [pustinek/ItemFilter#8]
https://github.com/rasclartdev/ItemFilter

found this, not sure if this is okay or not

**Comment by pustinek** [comment]
Hey,
Thanks for letting me know, I totally forgot to put a licensing file up for this project.
I will license it under MIT so he should be required to add it to the code he copied

**Comment by dpvb** [comment]
No problem mate.
He copied 3 of my repositories by straight up downloading the files and reuploading, he even has your name in some of the files (such as package declarations) in his first commit. Afterwards, he changes it to his name. The kid is scummy.
